### ISSUE TITLE
uncaught exception error

### ISSUE THREAD

**Issue by wasafiri** [joshsymonds/huey#12]
Any ideas? This is the error I see:

---

Uncaught exception: uninitialized constant Class::MultiJson
    /Users/x/.rvm/gems/ruby-2.0.0-p247/gems/huey-2.0.0/lib/huey/request.rb:24:in `register'
    /Users/x/.rvm/gems/ruby-2.0.0-p247/gems/huey-2.0.0/lib/huey/request.rb:14:in`block (2 levels) in singleton class'
    /Users/x/.rvm/gems/ruby-2.0.0-p247/gems/huey-2.0.0/lib/huey/bulb.rb:11:in `all'
    /Users/x/RubymineProjects/HUE controls/huelights:15:in`<top (required)>'

---

i'm running this script:

---

require 'huey'

time = Time.new
time.localtime

day = time.wday

weekday = day.between?(1, 5)

Huey.configure do |config|
  config.hue_ip = "192.168.1.16"
  config.ssdp = true
end

all = Huey::Group.new(bulbs: Huey::Bulb.all)

---

**Comment by thams** [comment]
Noticed the same thing. There is a dependency on a gem called 'multi_json', which isn't in huey's gemfile

Adding this to the Gemfile didn't quite solve it though; but pulling the huey gem to local file system did. Head scratcher.

**Comment by joshsymonds** [comment]
So this error is occurring in the currently released version of the Gem, though it's been fixed from about two weeks ago in issue https://github.com/Veraticus/huey/pull/10.

I'll release a new version tomorrow that includes this fix, so you won't have to manually set your source to this repository.

**Comment by joshsymonds** [comment]
@thams @wasafiri - I released Huey 2.1.0 today that includes the multi_json fix discussed in issue #10. So if you update now you shouldn't see any more issues.
