### ISSUE TITLE
Assigning bulb groups

### ISSUE THREAD

**Issue by wasafiri** [joshsymonds/huey#14]
There seems to be inconsistent behavior with assigning bulb groups.

Example:
g = Huey::Group.new(Huey::Bulb.find(1), Huey::Bulb.find(2), Huey::Bulb.find(3))
event = Huey::Event.new(name: 'All Lights Off', group: g, actions: {on: true}) #this will work
event.execute
###### 

all = Huey::Group.new(bulbs: Huey::Bulb.all)
event = Huey::Event.new(name: 'All Lights Off', group: all, actions: {on: true}) #this won't work
event.execute

It seems that using Huey::Bulb.all to assign a group causes events not to work when using that group.

**Comment by raspygold** [comment]
Looks like the readme needs updating. Instead of passing through a hash, use an array.
e.g. `all = Huey::Group.new(Huey::Bulb.all)`
