### ISSUE TITLE
How to keep in sync with bulb states?

### ISSUE THREAD

**Issue by jShaf** [joshsymonds/huey#8]
Using Huey, I change the color of a bulb to, say, Purple. If I change the color to Green using Hue iOS, how do I refresh/update the states of the bulb in Huey so I know the bulb is now showing Green?

Also, how do I know if the bulb is no longer lit as it may be switched off? 

Thanks!

**Comment by joshsymonds** [comment]
Presently there is no way to do that, but it wouldn't be difficult to add one. I'll do so later today.

**Comment by jShaf** [comment]
Sweet :D

**Comment by joshsymonds** [comment]
Now you can do bulb.refresh to get its state from the hub again.

**Comment by jShaf** [comment]
#reload works after building a gem manually since the published gem is still on 1.1.0. 

Thanks for fast work!
