### ISSUE TITLE
Huey does not connect to local bridge

### ISSUE THREAD

**Issue by resistorsoftware** [joshsymonds/huey#9]
Simple test. From my MBP on the local network I am telling Huey to connect directly to a bridge at 192.168.2.30 and it errors out with the **register and press the link button** message. The link button does not blink or acknowledge any incoming requests. Pressing it does not allow any Huey connections. Any suggestions?

```
require 'huey'
Huey.configure do |config|
  # Huey now uses the Phillips Hue API to discover local bridges, but you can specify the Hue IP
  # manually if your Huey server is not on your local network.
  config.hue_ip = '192.168.2.30'

  # SSDP is disabled by default.
  config.ssdp = true

  # For discovering the Hue hub, usually you won't have to change this.
  config.ssdp_ip = '239.255.255.250'

  # Also for discovering the Hue hub.
  config.ssdp_port = 1900

  # If you get constant errors about not being able to find the Hue hub and you're sure
  # it's connected, increase this.
  config.ssdp_ttl = 10

  # Change this if you don't like the included uuid.
  config.uuid = '0123456789abdcef0123456789abcdef'
end

bulbs = Huey::Bulb.all # Returns an array of your bulbs
```

**Comment by joshsymonds** [comment]
@resistorsoftware Try removing the IP address and letting Huey autodetect it from the Phillips Hue API. The hue_ip option is more present for people who are hosting Huey on somewhere that isn't their local network.

**Comment by resistorsoftware** [comment]
Thanks! Worked like peach removing that IP setup... W00t! Lightbulb fun times coming up.
